### ISSUE TITLE
Is there a plan to upgrade this module?

### ISSUE THREAD

**Issue by bhaidar** [aspnetboilerplate/sample-blog-module#7]
Hi,
I am trying to create my modules as separate modules so that it will be easy for me to upgrade original downloaded project once you release a new version of aspnetzero.

Is there a plan to upgrade this module and at least provide a simple step by step guide how to create our own modules separate from the framework files?

Thanks

**Comment by hikalkan** [comment]
While this sample is a bit old, same principle will work with the latest version. It's hard for us to upgrade all samples since we are frequently releasing new versions.

Actually we are working for more modular approach and created a simple sample: https://github.com/aspnetboilerplate/modular-todo-app We will create an article when have time.
